### ISSUE TITLE
Jetty dependencies issues

### ISSUE THREAD

**Issue by AndreaCrotti** [bhauman/figwheel-main#187]
I'm struggling getting the following libraries to work together:

- ring 1.7.1
- figwheel-main 0.20
- com.cognitect.aws/api 0.8.305

The problem is that for ring the newer ring will not work with an older version of jetty-server, but figwheel-main does not work with jetty-server >= 9.4
I tried all possible exclude tricks but can't really get it working, I think figwheel-main should just work with the most recent jetty right?

Thanks

See for example this error

```
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at figwheel.main$_main$fn__8071.invoke(main.cljc:2197)
	at clojure.core$with_redefs_fn.invokeStatic(core.clj:7514)
	at clojure.core$with_redefs_fn.invoke(core.clj:7498)
	at figwheel.main$_main.invokeStatic(main.cljc:2195)
	at figwheel.main$_main.doInvoke(main.cljc:2174)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval13303.invokeStatic(form-init8906574182605890035.clj:1)
	at user$eval13303.invoke(form-init8906574182605890035.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ConcurrentArrayQueue
	at org.eclipse.jetty.websocket.common.extensions.fragment.FragmentExtension.<init>(FragmentExtension.java:44)```

**Comment by bhauman** [comment]
https://figwheel.org/docs/jetty_conflicts.html

**Comment by AndreaCrotti** [comment]
Ah thanks, sorry I didn't see that. I did actually try the SNAPSHOT but I got a different error, I'll try again and see if I can get it working with the snapshot again.

**Comment by AndreaCrotti** [comment]
So if I try to use the SNAPSHOT sadly it doesn't work at all, simply the websocket is unable to connect.
I can't see any actual errors in the CLJS (which stays in pending state) repl though, any ideas?

I was trying if I could just locally get rid of the ring-jetty dependency but that breaks everything of course.
Would be nice to have a way to not require that, since I'm also using my own ring handler here.

This is the (not very helpful I know) error I get with 0.2.1-SNAPSHOT btw
```
websocket.js:283 WebSocket connection to 'ws://localhost:9503/figwheel-connect?fwprocess=6b8c2f&fwbuild=dev&fwsid=4b61b708-c4e0-4e72-b1fb-476d1d3c4f9b&fwsname=Angila' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED```

**Comment by AndreaCrotti** [comment]
I can close this now, it seems fine
